const CHANGE_STATE_GROUPS = 'CHANGE_STATE_GROUPS';
const CHANGE_STATE_FAVORITES_ADD = 'CHANGE_STATE_FAVORITES_ADD';
const CHANGE_STATE_FAVORITES_REMOVE = 'CHANGE_STATE_FAVORITES_REMOVE';

export {CHANGE_STATE_GROUPS, CHANGE_STATE_FAVORITES_ADD, CHANGE_STATE_FAVORITES_REMOVE};